-- MySQL Script generated by MySQL Workbench
-- Wed Jan  4 03:49:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ursus_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ursus_db` ;

-- -----------------------------------------------------
-- Schema ursus_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ursus_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `ursus_db` ;

-- -----------------------------------------------------
-- Table `ursus_db`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ursus_db`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`productos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `idCategoria` INT(11) NOT NULL,
  `estado` VARCHAR(100) NOT NULL DEFAULT 'Disponible',
  `precio` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `ursus_db`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_productos_categorias` ON `ursus_db`.`productos` (`idCategoria`);


-- -----------------------------------------------------
-- Table `ursus_db`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`tipo_usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ursus_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `imagenUser` VARCHAR(250) NOT NULL,
  `idTipoUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idTipoUsuario`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `ursus_db`.`tipo_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_idTipoUsuario` ON `ursus_db`.`usuarios` (`idTipoUsuario`);


-- -----------------------------------------------------
-- Table `ursus_db`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`carrito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idProducto` INT(11) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idProducto_c`
    FOREIGN KEY (`idProducto`)
    REFERENCES `ursus_db`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idUsuario_c`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ursus_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_idProducto_c` ON `ursus_db`.`carrito` (`idProducto`);

CREATE INDEX `fk_idUsuario_c` ON `ursus_db`.`carrito` (`idUsuario`);


-- -----------------------------------------------------
-- Table `ursus_db`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`generos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ursus_db`.`productos_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`productos_generos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idProducto` INT(11) NOT NULL,
  `idGenero` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Genero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `ursus_db`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prod`
    FOREIGN KEY (`idProducto`)
    REFERENCES `ursus_db`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_Prod_idx` ON `ursus_db`.`productos_generos` (`idProducto`);

CREATE INDEX `fk_Genero_idx` ON `ursus_db`.`productos_generos` (`idGenero`);


-- -----------------------------------------------------
-- Table `ursus_db`.`talles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`talles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ursus_db`.`productos_talles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ursus_db`.`productos_talles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idProducto` INT(11) NOT NULL,
  `idTalle` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Talles`
    FOREIGN KEY (`idTalle`)
    REFERENCES `ursus_db`.`talles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prodT`
    FOREIGN KEY (`idProducto`)
    REFERENCES `ursus_db`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_prodT_idx` ON `ursus_db`.`productos_talles` (`idProducto`);

CREATE INDEX `fk_Talles_idx` ON `ursus_db`.`productos_talles` (`idTalle`);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
